const STATE = {
    DISPLAY_VINEYARD: 0,
    DISPLAY_PLOT: 1,
    ADD_PLOT_SECTION: 2,
    EDIT_PLOT_SECTION: 3,
    EDIT_LINES_GLOBAL_PLACEMENT: 4,
    EDIT_LINES: 5,
    ADD_LINE: 6,
    REMOVE_LINE: 7,
    SELECT_LINES: 8
}

const MOUSE_BUTTONS = {
    LEFT_CLICK: 0,
    MIDDLE_CLICK: 1,
    RIGHT_CLICK: 2,
}

export {
    STATE,
    MOUSE_BUTTONS
}